version: '2'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.0.1
    stdin_open: true
    volumes:
    - /srv/logstash/:/usr/share/logstash/pipeline
    tty: true
    ports:
    - 5000:5000/udp
    - 6000:6000/tcp
    labels:
      io.rancher.container.pull_image: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      bootstrap.memory_lock: 'true'
      cluster.name: elastic-cluster
      discovery.zen.minimum_master_nodes: '1'
      discovery.zen.ping.unicast.hosts: elasticsearch
      node.data: 'true'
      node.master: 'true'
      node.name: ''
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        hard: 262144
        soft: 262144
    stdin_open: true
    volumes:
    - /srv/data/elasticsearch:/usr/share/elasticsearch/data
    tty: true
    ports:
    - 9200:9200/tcp
    labels:
      io.rancher.container.pull_image: always
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    stdin_open: true
    tty: true
    links:
    - elasticsearch:elasticsearch
    ports:
    - 80:5601/tcp
    labels:
      io.rancher.container.pull_image: always
